title: AJ Garcia # your name (or website title) here
logo: "/images/avatarmaker.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This portfolio was created for my web design class 
  <br><br>
  I hope you enjoy my portfolio as it is one of my first big design projects 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
